### ISSUE TITLE
Configure cannot find FFTW3 automatically

### ISSUE THREAD

**Issue by ziotom78** [hpc4cmb/libmadam#3]
When running `configure` on my laptop (a 64-bit PC running Linux Mint 17.2), the following error happens:

```
**** Enabling FFTW support.
checking fftw3.f03 fortran 90 header... find: `NONE': No such file or directory
not found
```

To install the FFTW library file, I used `apt-get` to install the package in Lint's repositories, which is in the standard location `/usr/lib/x86_64-linux-gnu/libfftw3.*`. The problem can be fixed by passing `--with-fftw=/usr` to `configure`:

```
./configure --with-fftw=/usr
```

However, it would be nice if the `configure` script would work it out for itself.

Things don't go smooth with `--with-fftw`, however, as `configure` now fails with another error, which I report on this page because I suspect it shares the same cause with the issue above:

```
checking fftw3.f03 fortran 90 header... not found
configure: error: in `/home/tomasi/tmp/libmadam/build2':
configure: error: fftw3.f03 is required.
```

I am not a `gfortran` expert, so I do not know why `configure` is not able to find this header in such a standard location as `/usr/include`. I brutally fixed this problem by copying `fftw3.f03` manually into `libmadam`'s source directory:

```
cp /usr/include/fftw3.f03 ./src
```

With this trick (and `--with-fftw`) I have been able to configure and compile `libmadam` correctly on my Linux laptop.

**Comment by tskisner** [comment]
Hi there, I believe Reijo saw this on his ubuntu install, but somehow mine worked.  The autoconf macro that looks for fortran include files uses a "hack" to try to find include directories to search for.  What it does is to parse $LD_LIBRARY_PATH, go up one directory from each entry, and search those directories.  Basically the reason for this stuff is that gfortran does not use the $CPATH environment variable to search for include files (unlike gcc / g++ which do).

One solution would be to change the FFTW autoconf macro to look also for the f03 include file- since that is where we have information about the FFTW install prefix.  However, since Reijo put all this together, I'll let him solve it however he wants.  As you note, a workaround is to _always_ specify the --with-fftw configure option.

**Comment by keskitalo** [comment]
I believe this issue is now obsolete. libmadam compiles fine on my Ubuntu partition against apt-get fftw3.
